### ISSUE TITLE
Hi, very interesting dev... 

### ISSUE THREAD

**Issue by GrCOTE7** [betaWeb/NestedJS#1]
Please could you see the Readme of... :

https://github.com/GrCOTE7/vh.git

I'm a noob, but used here interval technology to compute the tree and css to represent it. 

Perhaps we can do something very good with js instead of php... 

Sorry 4 my bad English, I'm French...

**Comment by betaWeb** [comment]
Salut,

Je suis également français, donc tu peux m'exposer ta problématique directement dans la langue de Molière :)
